language: node_js
node_js:
    - 13

jobs:
  include:
    - stage: test
      script:
        - npm install -g codecov
        - npm run lint
        - npm run cover
      after_success:
        - codecov
    - stage: build
      script:
        - npm run build
  allow_failures:
    - stage: deploy
      if: branch = master
      allow_failures:
        script:
          - npm publish
